### ISSUE TITLE
include directory dos not exist

### ISSUE THREAD

**Issue by kakrood** [Tuhin-SnapD/Prison-Management-System#1]

**Comment by Tuhin-SnapD** [comment]
Could you please elaborate your issue?

The software seems to be running properly, kindly share some screenshots or elaborate your issue

**Comment by Shantanu9402** [comment]
Where is the include directory? if we login as a officer, the requested file not found error appears, so pls kindly tell us where is the include directory or weather we have to create it?
![issue](https://user-images.githubusercontent.com/110244182/233853881-c57aca7e-157a-4e76-8463-1e7024c77ca0.PNG)

**Comment by Tuhin-SnapD** [comment]
https://drive.google.com/file/d/14ej1BfgTBCjmaFu6XBfbyVsG9pgOIFu9/view?usp=share_link User Portal
https://drive.google.com/file/d/1NsyHu1ciS4WsVOxwgrGzIPVbT-aTw8XK/view?usp=share_link  Admin Portal

I think you are asking for the sql file, download this from the provided link and save it in your directory, make sure to import it in your myphp page as well (localhost) , and surely let me know if there is any problem.

**Comment by Tuhin-SnapD** [comment]
Regarding include directory, the include directory is yet to be done, we will have to create, kindly create a pull request and make your improvements, thank you.

**Comment by Shantanu9402** [comment]
can we login to the dashboard without include directory ? if yes then what are the steps?
if not then what we have to mention in officer.login.inc.php? pls let us know?

**Comment by Tuhin-SnapD** [comment]
https://github.com/Tuhin-SnapD/Prison-Management-System

I have reworked the code, kindly try using this and surely let me know if this works.

**Comment by Tuhin-SnapD** [comment]
I have added the necessary files in the repository, it seems to be working fine, kindly let me know if it works.

**Comment by Shantanu9402** [comment]
Thank u so much sir, the system is working properly and everything seems to be fine and i am very grateful for your response.
